/**
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.accounting.apis

import dev.merge.client.accounting.models.MetaResponse
import dev.merge.client.accounting.models.PurchaseOrder
import dev.merge.client.accounting.models.PurchaseOrderEndpointRequest
import dev.merge.client.accounting.models.PurchaseOrderResponse

import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.serialization.jackson.jackson
import io.ktor.client.call.body
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.future.future
import java.util.concurrent.CompletableFuture

import com.fasterxml.jackson.databind.ObjectMapper

import dev.merge.client.shared.*

open class PurchaseOrdersApi(
baseUrl: String = ApiClient.BASE_URL + "accounting/v1",
httpClientEngine: HttpClientEngine? = null,
httpClientConfig: (HttpClientConfig<*>.() -> Unit)? = null,
json: ObjectMapper = ApiClient.JSON_DEFAULT,
) : ApiClient(baseUrl, httpClientEngine, httpClientConfig, json) {

    data class PurchaseOrdersCreateRequest (
        val purchaseOrderEndpointRequest: PurchaseOrderEndpointRequest,
        val isDebugMode: kotlin.Boolean? = null,
        val runAsync: kotlin.Boolean? = null
    )

    data class PurchaseOrdersListRequest (
        val createdAfter: java.time.OffsetDateTime? = null,
        val createdBefore: java.time.OffsetDateTime? = null,
        val cursor: kotlin.String? = null,
        val expand: kotlin.String? = null,
        val includeDeletedData: kotlin.Boolean? = null,
        val includeRemoteData: kotlin.Boolean? = null,
        val modifiedAfter: java.time.OffsetDateTime? = null,
        val modifiedBefore: java.time.OffsetDateTime? = null,
        val pageSize: kotlin.Int? = null,
        val remoteFields: kotlin.String? = null,
        val remoteId: kotlin.String? = null
    )

    data class PurchaseOrdersRetrieveRequest (
        val id: java.util.UUID,
        val expand: kotlin.String? = null,
        val includeRemoteData: kotlin.Boolean? = null,
        val remoteFields: kotlin.String? = null
    )

    /**
    * 
    * Creates a &#x60;PurchaseOrder&#x60; object with the given values.
     * @param purchaseOrderEndpointRequest  
     * @param isDebugMode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param runAsync Whether or not third-party updates should be run asynchronously. (optional)
     * @return PurchaseOrderResponse
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun purchaseOrdersCreate(requestModel: PurchaseOrdersApi.PurchaseOrdersCreateRequest): PurchaseOrderResponse {
        return purchaseOrdersCreateImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun purchaseOrdersCreateAsync(requestModel: PurchaseOrdersApi.PurchaseOrdersCreateRequest): CompletableFuture<PurchaseOrderResponse> = GlobalScope.future {
        purchaseOrdersCreate(requestModel)
    }

    /**
     * @param purchaseOrderEndpointRequest   * @param isDebugMode Whether to include debug fields (such as log file links) in the response. (optional) * @param runAsync Whether or not third-party updates should be run asynchronously. (optional)
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun purchaseOrdersCreateExpanded(requestModel: PurchaseOrdersApi.PurchaseOrdersCreateRequest): PurchaseOrderResponse.Expanded {
        return purchaseOrdersCreateImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun purchaseOrdersCreateExpandedAsync(requestModel: PurchaseOrdersApi.PurchaseOrdersCreateRequest): CompletableFuture<PurchaseOrderResponse.Expanded> = GlobalScope.future {
        purchaseOrdersCreateExpanded(requestModel)
    }

    private suspend inline fun <reified T> purchaseOrdersCreateImpl(requestModel: PurchaseOrdersApi.PurchaseOrdersCreateRequest): T {

        val localVariableAuthNames = listOf<String>("accountTokenAuth", "bearerAuth")

        val localVariableBody = requestModel.purchaseOrderEndpointRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
            requestModel.isDebugMode?.apply { localVariableQuery["is_debug_mode"] = listOf("$this") }
            requestModel.runAsync?.apply { localVariableQuery["run_async"] = listOf("$this") }

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
        RequestMethod.POST,
        "/purchase-orders",
        query = localVariableQuery,
        headers = localVariableHeaders
        )

        return jsonRequest(
        localVariableConfig,
        localVariableBody,
        localVariableAuthNames
        ).body()
    }

    /**
    * 
    * Returns a list of &#x60;PurchaseOrder&#x60; objects.
     * @param createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param cursor The pagination cursor value. (optional)
     * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional)
     * @param includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param modifiedAfter If provided, will only return objects modified after this datetime. (optional)
     * @param modifiedBefore If provided, will only return objects modified before this datetime. (optional)
     * @param pageSize Number of results to return per page. (optional)
     * @param remoteFields Which fields should be returned in non-normalized form. (optional)
     * @param remoteId The API provider&#39;s ID for the given object. (optional)
     * @return PaginatedPurchaseOrderList
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun purchaseOrdersList(requestModel: PurchaseOrdersApi.PurchaseOrdersListRequest): MergePaginatedResponse<PurchaseOrder> {
        return purchaseOrdersListImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun purchaseOrdersListAsync(requestModel: PurchaseOrdersApi.PurchaseOrdersListRequest): CompletableFuture<MergePaginatedResponse<PurchaseOrder>> = GlobalScope.future {
        purchaseOrdersList(requestModel)
    }

    /**
     * @param createdAfter If provided, will only return objects created after this datetime. (optional) * @param createdBefore If provided, will only return objects created before this datetime. (optional) * @param cursor The pagination cursor value. (optional) * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional) * @param includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional) * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional) * @param modifiedAfter If provided, will only return objects modified after this datetime. (optional) * @param modifiedBefore If provided, will only return objects modified before this datetime. (optional) * @param pageSize Number of results to return per page. (optional) * @param remoteFields Which fields should be returned in non-normalized form. (optional) * @param remoteId The API provider&#39;s ID for the given object. (optional)
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun purchaseOrdersListExpanded(requestModel: PurchaseOrdersApi.PurchaseOrdersListRequest): MergePaginatedResponse<PurchaseOrder.Expanded> {
        return purchaseOrdersListImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun purchaseOrdersListExpandedAsync(requestModel: PurchaseOrdersApi.PurchaseOrdersListRequest): CompletableFuture<MergePaginatedResponse<PurchaseOrder.Expanded>> = GlobalScope.future {
        purchaseOrdersListExpanded(requestModel)
    }

    private suspend inline fun <reified T> purchaseOrdersListImpl(requestModel: PurchaseOrdersApi.PurchaseOrdersListRequest): T {

        val localVariableAuthNames = listOf<String>("accountTokenAuth", "bearerAuth")

        val localVariableBody = 
                io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
            requestModel.createdAfter?.apply { localVariableQuery["created_after"] = listOf("$this") }
            requestModel.createdBefore?.apply { localVariableQuery["created_before"] = listOf("$this") }
            requestModel.cursor?.apply { localVariableQuery["cursor"] = listOf(this) }
            requestModel.expand?.apply { localVariableQuery["expand"] = listOf(this) }
            requestModel.includeDeletedData?.apply { localVariableQuery["include_deleted_data"] = listOf("$this") }
            requestModel.includeRemoteData?.apply { localVariableQuery["include_remote_data"] = listOf("$this") }
            requestModel.modifiedAfter?.apply { localVariableQuery["modified_after"] = listOf("$this") }
            requestModel.modifiedBefore?.apply { localVariableQuery["modified_before"] = listOf("$this") }
            requestModel.pageSize?.apply { localVariableQuery["page_size"] = listOf("$this") }
            requestModel.remoteFields?.apply { localVariableQuery["remote_fields"] = listOf(this) }
            requestModel.remoteId?.apply { localVariableQuery["remote_id"] = listOf(this) }

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
        RequestMethod.GET,
        "/purchase-orders",
        query = localVariableQuery,
        headers = localVariableHeaders
        )

        return request(
        localVariableConfig,
        localVariableBody,
        localVariableAuthNames
        ).body()
    }

    /**
    * 
    * Returns metadata for &#x60;PurchaseOrder&#x60; POSTs.
     * @return MetaResponse
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun purchaseOrdersMetaPostRetrieve(): MetaResponse {
        return purchaseOrdersMetaPostRetrieveImpl()
    }

    @Suppress("UNCHECKED_CAST")
    open fun purchaseOrdersMetaPostRetrieveAsync(): CompletableFuture<MetaResponse> = GlobalScope.future {
        purchaseOrdersMetaPostRetrieve()
    }

    /**
    
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun purchaseOrdersMetaPostRetrieveExpanded(): MetaResponse.Expanded {
        return purchaseOrdersMetaPostRetrieveImpl()
    }

    @Suppress("UNCHECKED_CAST")
    open fun purchaseOrdersMetaPostRetrieveExpandedAsync(): CompletableFuture<MetaResponse.Expanded> = GlobalScope.future {
        purchaseOrdersMetaPostRetrieveExpanded()
    }

    private suspend inline fun <reified T> purchaseOrdersMetaPostRetrieveImpl(): T {

        val localVariableAuthNames = listOf<String>("accountTokenAuth", "bearerAuth")

        val localVariableBody = 
                io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
        RequestMethod.GET,
        "/purchase-orders/meta/post",
        query = localVariableQuery,
        headers = localVariableHeaders
        )

        return request(
        localVariableConfig,
        localVariableBody,
        localVariableAuthNames
        ).body()
    }

    /**
    * 
    * Returns a &#x60;PurchaseOrder&#x60; object with the given &#x60;id&#x60;.
     * @param id  
     * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional)
     * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param remoteFields Which fields should be returned in non-normalized form. (optional)
     * @return PurchaseOrder
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun purchaseOrdersRetrieve(requestModel: PurchaseOrdersApi.PurchaseOrdersRetrieveRequest): PurchaseOrder {
        return purchaseOrdersRetrieveImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun purchaseOrdersRetrieveAsync(requestModel: PurchaseOrdersApi.PurchaseOrdersRetrieveRequest): CompletableFuture<PurchaseOrder> = GlobalScope.future {
        purchaseOrdersRetrieve(requestModel)
    }

    /**
     * @param id   * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional) * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional) * @param remoteFields Which fields should be returned in non-normalized form. (optional)
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun purchaseOrdersRetrieveExpanded(requestModel: PurchaseOrdersApi.PurchaseOrdersRetrieveRequest): PurchaseOrder.Expanded {
        return purchaseOrdersRetrieveImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun purchaseOrdersRetrieveExpandedAsync(requestModel: PurchaseOrdersApi.PurchaseOrdersRetrieveRequest): CompletableFuture<PurchaseOrder.Expanded> = GlobalScope.future {
        purchaseOrdersRetrieveExpanded(requestModel)
    }

    private suspend inline fun <reified T> purchaseOrdersRetrieveImpl(requestModel: PurchaseOrdersApi.PurchaseOrdersRetrieveRequest): T {

        val localVariableAuthNames = listOf<String>("accountTokenAuth", "bearerAuth")

        val localVariableBody = 
                io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
            requestModel.expand?.apply { localVariableQuery["expand"] = listOf(this) }
            requestModel.includeRemoteData?.apply { localVariableQuery["include_remote_data"] = listOf("$this") }
            requestModel.remoteFields?.apply { localVariableQuery["remote_fields"] = listOf(this) }

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
        RequestMethod.GET,
        "/purchase-orders/{id}".replace("{" + "id" + "}", "$requestModel.id"),
        query = localVariableQuery,
        headers = localVariableHeaders
        )

        return request(
        localVariableConfig,
        localVariableBody,
        localVariableAuthNames
        ).body()
    }

}
