/**
 * Merge Marketing Automation API
 *
 * The unified API for building rich integrations with multiple Marketing Automation platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.mktg.models


import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import dev.merge.client.shared.ApiClient

/**
 * # The Event Object ### Description The `Event` object is used to represent a marketing event, such as a webinar or email, in the remote system. ### Usage Example Fetch from the `GET /api/mktg/v1/events` endpoint and view their type properties.
 *
 * @param emails The marketing emails about this event.
 * @param messages The messages about this event.
 * @param name The event's name.
 * @param description The event's description.
 * @param remoteCreatedAt When the event was created in the remote system.
 * @param startTime When the event starts.
 * @param endTime When the event ends.
 * @param id 
 * @param remoteId The third-party API ID of the matching object.
 */

@JsonIgnoreProperties(ignoreUnknown = true)
data class Event (

    /* The marketing emails about this event. */
    @field:JsonProperty("emails")
    val emails: kotlin.collections.List<java.util.UUID>,

    /* The messages about this event. */
    @field:JsonProperty("messages")
    val messages: kotlin.collections.List<java.util.UUID>,

    /* The event's name. */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* The event's description. */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* When the event was created in the remote system. */
    @field:JsonProperty("remote_created_at")
    val remoteCreatedAt: java.time.OffsetDateTime? = null,

    /* When the event starts. */
    @field:JsonProperty("start_time")
    val startTime: java.time.OffsetDateTime? = null,

    /* When the event ends. */
    @field:JsonProperty("end_time")
    val endTime: java.time.OffsetDateTime? = null,

    @field:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* The third-party API ID of the matching object. */
    @field:JsonProperty("remote_id")
    val remoteId: kotlin.String? = null

) {

    @JsonIgnoreProperties(ignoreUnknown = true)
    data class Expanded(
        @field:JsonProperty("emails")
        val emails: kotlin.collections.List<JsonNode>,

        @field:JsonProperty("messages")
        val messages: kotlin.collections.List<JsonNode>,

        @field:JsonProperty("name")
        val name: JsonNode?,

        @field:JsonProperty("description")
        val description: JsonNode?,

        @field:JsonProperty("remote_created_at")
        val remoteCreatedAt: JsonNode?,

        @field:JsonProperty("start_time")
        val startTime: JsonNode?,

        @field:JsonProperty("end_time")
        val endTime: JsonNode?,

        @field:JsonProperty("id")
        val id: JsonNode?,

        @field:JsonProperty("remote_id")
        val remoteId: JsonNode?

    )


    companion object {
        @JvmStatic
        fun normalize(expanded: Event.Expanded): Event {
            return Event(
                emails = ApiClient.jsonConvertRequiredSafe(expanded.emails),
                messages = ApiClient.jsonConvertRequiredSafe(expanded.messages),
                name = ApiClient.jsonConvertSafe(expanded.name),
                description = ApiClient.jsonConvertSafe(expanded.description),
                remoteCreatedAt = ApiClient.jsonConvertSafe(expanded.remoteCreatedAt),
                startTime = ApiClient.jsonConvertSafe(expanded.startTime),
                endTime = ApiClient.jsonConvertSafe(expanded.endTime),
                id = ApiClient.jsonConvertSafe(expanded.id),
                remoteId = ApiClient.jsonConvertSafe(expanded.remoteId)
            )
        }
    }
}

