/**
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.ticketing.apis

import dev.merge.client.ticketing.models.Collection
import dev.merge.client.ticketing.models.User

import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.serialization.jackson.jackson
import io.ktor.client.call.body
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.future.future
import java.util.concurrent.CompletableFuture

import com.fasterxml.jackson.databind.ObjectMapper

import dev.merge.client.shared.*

open class CollectionsApi(
baseUrl: String = ApiClient.BASE_URL + "ticketing/v1",
httpClientEngine: HttpClientEngine? = null,
httpClientConfig: (HttpClientConfig<*>.() -> Unit)? = null,
json: ObjectMapper = ApiClient.JSON_DEFAULT,
) : ApiClient(baseUrl, httpClientEngine, httpClientConfig, json) {

    data class CollectionsListRequest (
        val collectionType: kotlin.String? = null,
        val createdAfter: java.time.OffsetDateTime? = null,
        val createdBefore: java.time.OffsetDateTime? = null,
        val cursor: kotlin.String? = null,
        val expand: kotlin.String? = null,
        val includeDeletedData: kotlin.Boolean? = null,
        val includeRemoteData: kotlin.Boolean? = null,
        val modifiedAfter: java.time.OffsetDateTime? = null,
        val modifiedBefore: java.time.OffsetDateTime? = null,
        val pageSize: kotlin.Int? = null,
        val parentCollectionId: kotlin.String? = null,
        val remoteFields: kotlin.String? = null,
        val remoteId: kotlin.String? = null,
        val showEnumOrigins: kotlin.String? = null
    )

    data class CollectionsRetrieveRequest (
        val id: java.util.UUID,
        val expand: kotlin.String? = null,
        val includeRemoteData: kotlin.Boolean? = null,
        val remoteFields: kotlin.String? = null,
        val showEnumOrigins: kotlin.String? = null
    )

    data class CollectionsUsersListRequest (
        val parentId: java.util.UUID,
        val cursor: kotlin.String? = null,
        val expand: kotlin.String? = null,
        val includeDeletedData: kotlin.Boolean? = null,
        val includeRemoteData: kotlin.Boolean? = null,
        val pageSize: kotlin.Int? = null
    )

    /**
    * 
    * Returns a list of &#x60;Collection&#x60; objects.
     * @param collectionType If provided, will only return collections of the given type.  * &#x60;LIST&#x60; - LIST * &#x60;PROJECT&#x60; - PROJECT (optional)
     * @param createdAfter If provided, will only return objects created after this datetime. (optional)
     * @param createdBefore If provided, will only return objects created before this datetime. (optional)
     * @param cursor The pagination cursor value. (optional)
     * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional)
     * @param includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param modifiedAfter If provided, only objects synced by Merge after this date time will be returned. (optional)
     * @param modifiedBefore If provided, only objects synced by Merge before this date time will be returned. (optional)
     * @param pageSize Number of results to return per page. (optional)
     * @param parentCollectionId If provided, will only return collections whose parent collection matches the given id. (optional)
     * @param remoteFields Deprecated. Use show_enum_origins. (optional)
     * @param remoteId The API provider&#39;s ID for the given object. (optional)
     * @param showEnumOrigins Which fields should be returned in non-normalized form. (optional)
     * @return PaginatedCollectionList
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun collectionsList(requestModel: CollectionsApi.CollectionsListRequest): MergePaginatedResponse<Collection> {
        return collectionsListImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun collectionsListAsync(requestModel: CollectionsApi.CollectionsListRequest): CompletableFuture<MergePaginatedResponse<Collection>> = GlobalScope.future {
        collectionsList(requestModel)
    }

    /**
     * @param collectionType If provided, will only return collections of the given type.  * &#x60;LIST&#x60; - LIST * &#x60;PROJECT&#x60; - PROJECT (optional) * @param createdAfter If provided, will only return objects created after this datetime. (optional) * @param createdBefore If provided, will only return objects created before this datetime. (optional) * @param cursor The pagination cursor value. (optional) * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional) * @param includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional) * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional) * @param modifiedAfter If provided, only objects synced by Merge after this date time will be returned. (optional) * @param modifiedBefore If provided, only objects synced by Merge before this date time will be returned. (optional) * @param pageSize Number of results to return per page. (optional) * @param parentCollectionId If provided, will only return collections whose parent collection matches the given id. (optional) * @param remoteFields Deprecated. Use show_enum_origins. (optional) * @param remoteId The API provider&#39;s ID for the given object. (optional) * @param showEnumOrigins Which fields should be returned in non-normalized form. (optional)
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun collectionsListExpanded(requestModel: CollectionsApi.CollectionsListRequest): MergePaginatedResponse<Collection.Expanded> {
        return collectionsListImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun collectionsListExpandedAsync(requestModel: CollectionsApi.CollectionsListRequest): CompletableFuture<MergePaginatedResponse<Collection.Expanded>> = GlobalScope.future {
        collectionsListExpanded(requestModel)
    }

    private suspend inline fun <reified T> collectionsListImpl(requestModel: CollectionsApi.CollectionsListRequest): T {

        val localVariableAuthNames = listOf<String>("accountTokenAuth", "bearerAuth")

        val localVariableBody = 
                io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
            requestModel.collectionType?.apply { localVariableQuery["collection_type"] = listOf(this) }
            requestModel.createdAfter?.apply { localVariableQuery["created_after"] = listOf("$this") }
            requestModel.createdBefore?.apply { localVariableQuery["created_before"] = listOf("$this") }
            requestModel.cursor?.apply { localVariableQuery["cursor"] = listOf(this) }
            requestModel.expand?.apply { localVariableQuery["expand"] = listOf(this) }
            requestModel.includeDeletedData?.apply { localVariableQuery["include_deleted_data"] = listOf("$this") }
            requestModel.includeRemoteData?.apply { localVariableQuery["include_remote_data"] = listOf("$this") }
            requestModel.modifiedAfter?.apply { localVariableQuery["modified_after"] = listOf("$this") }
            requestModel.modifiedBefore?.apply { localVariableQuery["modified_before"] = listOf("$this") }
            requestModel.pageSize?.apply { localVariableQuery["page_size"] = listOf("$this") }
            requestModel.parentCollectionId?.apply { localVariableQuery["parent_collection_id"] = listOf(this) }
            requestModel.remoteFields?.apply { localVariableQuery["remote_fields"] = listOf(this) }
            requestModel.remoteId?.apply { localVariableQuery["remote_id"] = listOf(this) }
            requestModel.showEnumOrigins?.apply { localVariableQuery["show_enum_origins"] = listOf(this) }

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
        RequestMethod.GET,
        "/collections",
        query = localVariableQuery,
        headers = localVariableHeaders
        )

        return request(
        localVariableConfig,
        localVariableBody,
        localVariableAuthNames
        ).body()
    }

    /**
    * 
    * Returns a &#x60;Collection&#x60; object with the given &#x60;id&#x60;.
     * @param id  
     * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional)
     * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param remoteFields Deprecated. Use show_enum_origins. (optional)
     * @param showEnumOrigins Which fields should be returned in non-normalized form. (optional)
     * @return Collection
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun collectionsRetrieve(requestModel: CollectionsApi.CollectionsRetrieveRequest): Collection {
        return collectionsRetrieveImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun collectionsRetrieveAsync(requestModel: CollectionsApi.CollectionsRetrieveRequest): CompletableFuture<Collection> = GlobalScope.future {
        collectionsRetrieve(requestModel)
    }

    /**
     * @param id   * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional) * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional) * @param remoteFields Deprecated. Use show_enum_origins. (optional) * @param showEnumOrigins Which fields should be returned in non-normalized form. (optional)
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun collectionsRetrieveExpanded(requestModel: CollectionsApi.CollectionsRetrieveRequest): Collection.Expanded {
        return collectionsRetrieveImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun collectionsRetrieveExpandedAsync(requestModel: CollectionsApi.CollectionsRetrieveRequest): CompletableFuture<Collection.Expanded> = GlobalScope.future {
        collectionsRetrieveExpanded(requestModel)
    }

    private suspend inline fun <reified T> collectionsRetrieveImpl(requestModel: CollectionsApi.CollectionsRetrieveRequest): T {

        val localVariableAuthNames = listOf<String>("accountTokenAuth", "bearerAuth")

        val localVariableBody = 
                io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
            requestModel.expand?.apply { localVariableQuery["expand"] = listOf(this) }
            requestModel.includeRemoteData?.apply { localVariableQuery["include_remote_data"] = listOf("$this") }
            requestModel.remoteFields?.apply { localVariableQuery["remote_fields"] = listOf(this) }
            requestModel.showEnumOrigins?.apply { localVariableQuery["show_enum_origins"] = listOf(this) }

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
        RequestMethod.GET,
        "/collections/{id}".replace("{" + "id" + "}", "${ requestModel.id }"),
        query = localVariableQuery,
        headers = localVariableHeaders
        )

        return request(
        localVariableConfig,
        localVariableBody,
        localVariableAuthNames
        ).body()
    }

    /**
    * 
    * Returns a list of &#x60;User&#x60; objects.
     * @param parentId  
     * @param cursor The pagination cursor value. (optional)
     * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional)
     * @param includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param pageSize Number of results to return per page. (optional)
     * @return PaginatedUserList
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun collectionsUsersList(requestModel: CollectionsApi.CollectionsUsersListRequest): MergePaginatedResponse<User> {
        return collectionsUsersListImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun collectionsUsersListAsync(requestModel: CollectionsApi.CollectionsUsersListRequest): CompletableFuture<MergePaginatedResponse<User>> = GlobalScope.future {
        collectionsUsersList(requestModel)
    }

    /**
     * @param parentId   * @param cursor The pagination cursor value. (optional) * @param expand Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces. (optional) * @param includeDeletedData Whether to include data that was marked as deleted by third party webhooks. (optional) * @param includeRemoteData Whether to include the original data Merge fetched from the third-party to produce these models. (optional) * @param pageSize Number of results to return per page. (optional)
    */
    @Suppress("UNCHECKED_CAST")
    open suspend fun collectionsUsersListExpanded(requestModel: CollectionsApi.CollectionsUsersListRequest): MergePaginatedResponse<User.Expanded> {
        return collectionsUsersListImpl(requestModel)
    }

    @Suppress("UNCHECKED_CAST")
    open fun collectionsUsersListExpandedAsync(requestModel: CollectionsApi.CollectionsUsersListRequest): CompletableFuture<MergePaginatedResponse<User.Expanded>> = GlobalScope.future {
        collectionsUsersListExpanded(requestModel)
    }

    private suspend inline fun <reified T> collectionsUsersListImpl(requestModel: CollectionsApi.CollectionsUsersListRequest): T {

        val localVariableAuthNames = listOf<String>("accountTokenAuth", "bearerAuth")

        val localVariableBody = 
                io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
            requestModel.cursor?.apply { localVariableQuery["cursor"] = listOf(this) }
            requestModel.expand?.apply { localVariableQuery["expand"] = listOf(this) }
            requestModel.includeDeletedData?.apply { localVariableQuery["include_deleted_data"] = listOf("$this") }
            requestModel.includeRemoteData?.apply { localVariableQuery["include_remote_data"] = listOf("$this") }
            requestModel.pageSize?.apply { localVariableQuery["page_size"] = listOf("$this") }

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
        RequestMethod.GET,
        "/collections/{parent_id}/users".replace("{" + "parent_id" + "}", "${ requestModel.parentId }"),
        query = localVariableQuery,
        headers = localVariableHeaders
        )

        return request(
        localVariableConfig,
        localVariableBody,
        localVariableAuthNames
        ).body()
    }

}
