/**
 * Merge ATS API
 *
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.ats.models

import dev.merge.client.ats.models.ReasonEnum

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param reason 
 * @param message 
 */

data class IgnoreCommonModelRequest (

    @field:JsonProperty("reason")
    val reason: ReasonEnum?,

    @field:JsonProperty("message")
    val message: kotlin.String? = null

)

