/**
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.hris.models


import com.fasterxml.jackson.annotation.JsonEnumDefaultValue
import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * Values: SINGLE,MARRIED_FILING_JOINTLY,MARRIED_FILING_SEPARATELY,HEAD_OF_HOUSEHOLD,QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD
 */
enum class MaritalStatusEnum(val value: kotlin.String) {

    @JsonEnumDefaultValue
    @JsonProperty(value = "MERGE_NONSTANDARD_VALUE")
    MERGE_NONSTANDARD_VALUE("MERGE_NONSTANDARD_VALUE"),


    @JsonProperty(value = "SINGLE")
    SINGLE("SINGLE"),


    @JsonProperty(value = "MARRIED_FILING_JOINTLY")
    MARRIED_FILING_JOINTLY("MARRIED_FILING_JOINTLY"),


    @JsonProperty(value = "MARRIED_FILING_SEPARATELY")
    MARRIED_FILING_SEPARATELY("MARRIED_FILING_SEPARATELY"),


    @JsonProperty(value = "HEAD_OF_HOUSEHOLD")
    HEAD_OF_HOUSEHOLD("HEAD_OF_HOUSEHOLD"),


    @JsonProperty(value = "QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD")
    QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD("QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD");


    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise. We do not encode to
         * MERGE_NONSTANDARD_VALUE since the API never expects to receive this value, so encoding it is not valid.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MaritalStatusEnum) "$data" else null

        /**
         * Returns a valid [MaritalStatusEnum] for [data], MERGE_NONSTANDARD_VALUE otherwise
         */
        fun decode(data: kotlin.Any?): MaritalStatusEnum = data?.let {
          val normalizedData = "$it".lowercase()
          return values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          } ?: MERGE_NONSTANDARD_VALUE
        } ?: MERGE_NONSTANDARD_VALUE
    }
}

