/**
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.hris.models

import dev.merge.client.shared.RemoteData
import dev.merge.client.hris.models.RequestTypeEnum
import dev.merge.client.hris.models.TimeOffStatusEnum
import dev.merge.client.hris.models.UnitsEnum

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import dev.merge.client.shared.ApiClient

/**
 * # The TimeOff Object ### Description The `TimeOff` object is used to represent all employees' Time Off entries.  ### Usage Example Fetch from the `LIST TimeOffs` endpoint and filter by `ID` to show all time off requests.
 *
 * @param id 
 * @param remoteId The third-party API ID of the matching object.
 * @param employee The employee requesting time off.
 * @param approver The Merge ID of the employee with the ability to approve the time off request.
 * @param status The status of this time off request.  * `REQUESTED` - REQUESTED * `APPROVED` - APPROVED * `DECLINED` - DECLINED * `CANCELLED` - CANCELLED * `DELETED` - DELETED
 * @param employeeNote The employee note for this time off request.
 * @param units The measurement that the third-party integration uses to count time requested.  * `HOURS` - HOURS * `DAYS` - DAYS
 * @param amount The time off quantity measured by the prescribed “units”.
 * @param requestType The type of time off request.  * `VACATION` - VACATION * `SICK` - SICK * `PERSONAL` - PERSONAL * `JURY_DUTY` - JURY_DUTY * `VOLUNTEER` - VOLUNTEER * `BEREAVEMENT` - BEREAVEMENT
 * @param startTime The day and time of the start of the time requested off.
 * @param endTime The day and time of the end of the time requested off.
 * @param remoteWasDeleted 
 * @param modifiedAt This is the datetime that this object was last updated by Merge
 * @param fieldMappings 
 * @param remoteData 
 */

@JsonIgnoreProperties(ignoreUnknown = true)
data class TimeOff (

    @field:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* The third-party API ID of the matching object. */
    @field:JsonProperty("remote_id")
    val remoteId: kotlin.String? = null,

    /* The employee requesting time off. */
    @field:JsonProperty("employee")
    val employee: java.util.UUID? = null,

    /* The Merge ID of the employee with the ability to approve the time off request. */
    @field:JsonProperty("approver")
    val approver: java.util.UUID? = null,

    /* The status of this time off request.  * `REQUESTED` - REQUESTED * `APPROVED` - APPROVED * `DECLINED` - DECLINED * `CANCELLED` - CANCELLED * `DELETED` - DELETED */
    @field:JsonProperty("status")
    val status: TimeOffStatusEnum? = null,

    /* The employee note for this time off request. */
    @field:JsonProperty("employee_note")
    val employeeNote: kotlin.String? = null,

    /* The measurement that the third-party integration uses to count time requested.  * `HOURS` - HOURS * `DAYS` - DAYS */
    @field:JsonProperty("units")
    val units: UnitsEnum? = null,

    /* The time off quantity measured by the prescribed “units”. */
    @field:JsonProperty("amount")
    val amount: kotlin.Double? = null,

    /* The type of time off request.  * `VACATION` - VACATION * `SICK` - SICK * `PERSONAL` - PERSONAL * `JURY_DUTY` - JURY_DUTY * `VOLUNTEER` - VOLUNTEER * `BEREAVEMENT` - BEREAVEMENT */
    @field:JsonProperty("request_type")
    val requestType: RequestTypeEnum? = null,

    /* The day and time of the start of the time requested off. */
    @field:JsonProperty("start_time")
    val startTime: java.time.OffsetDateTime? = null,

    /* The day and time of the end of the time requested off. */
    @field:JsonProperty("end_time")
    val endTime: java.time.OffsetDateTime? = null,

    @field:JsonProperty("remote_was_deleted")
    val remoteWasDeleted: kotlin.Boolean? = null,

    /* This is the datetime that this object was last updated by Merge */
    @field:JsonProperty("modified_at")
    val modifiedAt: java.time.OffsetDateTime? = null,

    @field:JsonProperty("field_mappings")
    val fieldMappings: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @field:JsonProperty("remote_data")
    val remoteData: kotlin.collections.List<RemoteData>? = null

) {

    @JsonIgnoreProperties(ignoreUnknown = true)
    data class Expanded(
        @field:JsonProperty("id")
        val id: JsonNode?,

        @field:JsonProperty("remote_id")
        val remoteId: JsonNode?,

        @field:JsonProperty("employee")
        val employee: JsonNode?,

        @field:JsonProperty("approver")
        val approver: JsonNode?,

        @field:JsonProperty("status")
        val status: JsonNode?,

        @field:JsonProperty("employee_note")
        val employeeNote: JsonNode?,

        @field:JsonProperty("units")
        val units: JsonNode?,

        @field:JsonProperty("amount")
        val amount: JsonNode?,

        @field:JsonProperty("request_type")
        val requestType: JsonNode?,

        @field:JsonProperty("start_time")
        val startTime: JsonNode?,

        @field:JsonProperty("end_time")
        val endTime: JsonNode?,

        @field:JsonProperty("remote_was_deleted")
        val remoteWasDeleted: JsonNode?,

        @field:JsonProperty("modified_at")
        val modifiedAt: JsonNode?,

        @field:JsonProperty("field_mappings")
        val fieldMappings: JsonNode?,

        @field:JsonProperty("remote_data")
        val remoteData: kotlin.collections.List<JsonNode>?

    )


    companion object {
        @JvmStatic
        fun normalize(expanded: TimeOff.Expanded): TimeOff {
            return TimeOff(
                id = ApiClient.jsonConvertSafe(expanded.id),
                remoteId = ApiClient.jsonConvertSafe(expanded.remoteId),
                employee = ApiClient.jsonConvertSafe(expanded.employee),
                approver = ApiClient.jsonConvertSafe(expanded.approver),
                status = ApiClient.jsonConvertSafe(expanded.status),
                employeeNote = ApiClient.jsonConvertSafe(expanded.employeeNote),
                units = ApiClient.jsonConvertSafe(expanded.units),
                amount = ApiClient.jsonConvertSafe(expanded.amount),
                requestType = ApiClient.jsonConvertSafe(expanded.requestType),
                startTime = ApiClient.jsonConvertSafe(expanded.startTime),
                endTime = ApiClient.jsonConvertSafe(expanded.endTime),
                remoteWasDeleted = ApiClient.jsonConvertSafe(expanded.remoteWasDeleted),
                modifiedAt = ApiClient.jsonConvertSafe(expanded.modifiedAt),
                fieldMappings = ApiClient.jsonConvertSafe(expanded.fieldMappings),
                remoteData = ApiClient.jsonConvertSafe(expanded.remoteData)
            )
        }
    }
}

