/**
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.accounting.models

import dev.merge.client.accounting.models.CreditNoteLineItem
import dev.merge.client.accounting.models.CreditNoteStatusEnum
import dev.merge.client.accounting.models.CurrencyEnum
import dev.merge.client.shared.RemoteData

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * # The CreditNote Object ### Description The `CreditNote` object is used to represent a refund or credit of payment.  ### Usage Example Fetch from the `LIST CreditNotes` endpoint and view a company's credit notes.
 *
 * @param id 
 * @param remoteId The third-party API ID of the matching object.
 * @param remoteData 
 * @param transactionDate The credit note's transaction date.
 * @param status The credit note's status.
 * @param number The credit note's number.
 * @param contact The credit note's contact.
 * @param totalAmount The credit note's total amount.
 * @param remainingCredit The credit note's remaining credit.
 * @param lineItems 
 * @param currency The credit note's currency.
 * @param remoteCreatedAt When the third party's credit note was created.
 * @param remoteUpdatedAt When the third party's credit note was updated.
 * @param payments Array of `Payment` object IDs
 * @param remoteWasDeleted Indicates whether or not this object has been deleted by third party webhooks.
 */

data class CreditNote (

    @field:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* The third-party API ID of the matching object. */
    @field:JsonProperty("remote_id")
    val remoteId: kotlin.String? = null,

    @field:JsonProperty("remote_data")
    val remoteData: kotlin.collections.List<RemoteData>? = null,

    /* The credit note's transaction date. */
    @field:JsonProperty("transaction_date")
    val transactionDate: java.time.OffsetDateTime? = null,

    /* The credit note's status. */
    @field:JsonProperty("status")
    val status: CreditNoteStatusEnum? = null,

    /* The credit note's number. */
    @field:JsonProperty("number")
    val number: kotlin.String? = null,

    /* The credit note's contact. */
    @field:JsonProperty("contact")
    val contact: java.util.UUID? = null,

    /* The credit note's total amount. */
    @field:JsonProperty("total_amount")
    val totalAmount: kotlin.Float? = null,

    /* The credit note's remaining credit. */
    @field:JsonProperty("remaining_credit")
    val remainingCredit: kotlin.Float? = null,

    @field:JsonProperty("line_items")
    val lineItems: kotlin.collections.List<CreditNoteLineItem>? = null,

    /* The credit note's currency. */
    @field:JsonProperty("currency")
    val currency: CurrencyEnum? = null,

    /* When the third party's credit note was created. */
    @field:JsonProperty("remote_created_at")
    val remoteCreatedAt: java.time.OffsetDateTime? = null,

    /* When the third party's credit note was updated. */
    @field:JsonProperty("remote_updated_at")
    val remoteUpdatedAt: java.time.OffsetDateTime? = null,

    /* Array of `Payment` object IDs */
    @field:JsonProperty("payments")
    val payments: kotlin.collections.List<java.util.UUID>? = null,

    /* Indicates whether or not this object has been deleted by third party webhooks. */
    @field:JsonProperty("remote_was_deleted")
    val remoteWasDeleted: kotlin.Boolean? = null

)

