/**
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.accounting.models


import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import dev.merge.client.shared.ApiClient

/**
 * # The VendorCreditLine Object ### Description The `VendorCreditLine` object is used to represent a vendor credit's line items.  ### Usage Example Fetch from the `GET VendorCredit` endpoint and view the vendor credit's line items.
 *
 * @param trackingCategories The line's associated tracking categories.
 * @param remoteId The third-party API ID of the matching object.
 * @param netAmount The full value of the credit.
 * @param trackingCategory The line's associated tracking category.
 * @param description The line's description.
 * @param account The line's account.
 * @param company The company the line belongs to.
 */

@JsonIgnoreProperties(ignoreUnknown = true)
data class VendorCreditLine (

    /* The line's associated tracking categories. */
    @field:JsonProperty("tracking_categories")
    val trackingCategories: kotlin.collections.List<java.util.UUID>,

    /* The third-party API ID of the matching object. */
    @field:JsonProperty("remote_id")
    val remoteId: kotlin.String? = null,

    /* The full value of the credit. */
    @field:JsonProperty("net_amount")
    val netAmount: kotlin.Float? = null,

    /* The line's associated tracking category. */
    @field:JsonProperty("tracking_category")
    val trackingCategory: java.util.UUID? = null,

    /* The line's description. */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* The line's account. */
    @field:JsonProperty("account")
    val account: java.util.UUID? = null,

    /* The company the line belongs to. */
    @field:JsonProperty("company")
    val company: java.util.UUID? = null

) {

    @JsonIgnoreProperties(ignoreUnknown = true)
    data class Expanded(
        @field:JsonProperty("tracking_categories")
        val trackingCategories: kotlin.collections.List<JsonNode>,

        @field:JsonProperty("remote_id")
        val remoteId: JsonNode?,

        @field:JsonProperty("net_amount")
        val netAmount: JsonNode?,

        @field:JsonProperty("tracking_category")
        val trackingCategory: JsonNode?,

        @field:JsonProperty("description")
        val description: JsonNode?,

        @field:JsonProperty("account")
        val account: JsonNode?,

        @field:JsonProperty("company")
        val company: JsonNode?

    )


    companion object {
        @JvmStatic
        fun normalize(expanded: VendorCreditLine.Expanded): VendorCreditLine {
            return VendorCreditLine(
                trackingCategories = ApiClient.jsonConvertRequiredSafe(expanded.trackingCategories),
                remoteId = ApiClient.jsonConvertSafe(expanded.remoteId),
                netAmount = ApiClient.jsonConvertSafe(expanded.netAmount),
                trackingCategory = ApiClient.jsonConvertSafe(expanded.trackingCategory),
                description = ApiClient.jsonConvertSafe(expanded.description),
                account = ApiClient.jsonConvertSafe(expanded.account),
                company = ApiClient.jsonConvertSafe(expanded.company)
            )
        }
    }
}

