/**
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.crm.models


import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import dev.merge.client.shared.ApiClient

/**
 * 
 *
 * @param conditionSchemaId The ID indicating which condition schema to use for a specific condition.
 * @param `operator` The operator for a specific condition.
 * @param `value` The value for a specific condition.
 */

@JsonIgnoreProperties(ignoreUnknown = true)
data class LinkedAccountConditionRequest (

    /* The ID indicating which condition schema to use for a specific condition. */
    @field:JsonProperty("condition_schema_id")
    val conditionSchemaId: java.util.UUID,

    /* The operator for a specific condition. */
    @field:JsonProperty("operator")
    val `operator`: kotlin.String,

    /* The value for a specific condition. */
    @field:JsonProperty("value")
    val `value`: kotlin.Any?

) {

    @JsonIgnoreProperties(ignoreUnknown = true)
    data class Expanded(
        @field:JsonProperty("condition_schema_id")
        val conditionSchemaId: JsonNode,

        @field:JsonProperty("operator")
        val `operator`: JsonNode,

        @field:JsonProperty("value")
        val `value`: JsonNode

    )


    companion object {
        @JvmStatic
        fun normalize(expanded: LinkedAccountConditionRequest.Expanded): LinkedAccountConditionRequest {
            return LinkedAccountConditionRequest(
                conditionSchemaId = ApiClient.jsonConvertRequiredSafe(expanded.conditionSchemaId),
                `operator` = ApiClient.jsonConvertRequiredSafe(expanded.`operator`),
                `value` = ApiClient.jsonConvertRequiredSafe(expanded.`value`)
            )
        }
    }
}

