/**
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.merge.client.crm.models

import dev.merge.client.crm.models.FieldFormatEnum
import dev.merge.client.crm.models.FieldTypeEnum
import dev.merge.client.crm.models.ItemSchema

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import dev.merge.client.shared.ApiClient

/**
 * 
 *
 * @param id 
 * @param displayName 
 * @param remoteKeyName 
 * @param description 
 * @param isCustom 
 * @param isRequired 
 * @param fieldType 
 * @param fieldFormat 
 * @param fieldChoices 
 * @param itemSchema 
 */

@JsonIgnoreProperties(ignoreUnknown = true)
data class RemoteFieldClass (

    @field:JsonProperty("id")
    val id: kotlin.String? = null,

    @field:JsonProperty("display_name")
    val displayName: kotlin.String? = null,

    @field:JsonProperty("remote_key_name")
    val remoteKeyName: kotlin.String? = null,

    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    @field:JsonProperty("is_custom")
    val isCustom: kotlin.Boolean? = null,

    @field:JsonProperty("is_required")
    val isRequired: kotlin.Boolean? = null,

    @field:JsonProperty("field_type")
    val fieldType: FieldTypeEnum? = null,

    @field:JsonProperty("field_format")
    val fieldFormat: FieldFormatEnum? = null,

    @field:JsonProperty("field_choices")
    val fieldChoices: kotlin.collections.List<kotlin.String>? = null,

    @field:JsonProperty("item_schema")
    val itemSchema: ItemSchema? = null

) {

    @JsonIgnoreProperties(ignoreUnknown = true)
    data class Expanded(
        @field:JsonProperty("id")
        val id: JsonNode?,

        @field:JsonProperty("display_name")
        val displayName: JsonNode?,

        @field:JsonProperty("remote_key_name")
        val remoteKeyName: JsonNode?,

        @field:JsonProperty("description")
        val description: JsonNode?,

        @field:JsonProperty("is_custom")
        val isCustom: JsonNode?,

        @field:JsonProperty("is_required")
        val isRequired: JsonNode?,

        @field:JsonProperty("field_type")
        val fieldType: JsonNode?,

        @field:JsonProperty("field_format")
        val fieldFormat: JsonNode?,

        @field:JsonProperty("field_choices")
        val fieldChoices: kotlin.collections.List<JsonNode>?,

        @field:JsonProperty("item_schema")
        val itemSchema: JsonNode?

    )


    companion object {
        @JvmStatic
        fun normalize(expanded: RemoteFieldClass.Expanded): RemoteFieldClass {
            return RemoteFieldClass(
                id = ApiClient.jsonConvertSafe(expanded.id),
                displayName = ApiClient.jsonConvertSafe(expanded.displayName),
                remoteKeyName = ApiClient.jsonConvertSafe(expanded.remoteKeyName),
                description = ApiClient.jsonConvertSafe(expanded.description),
                isCustom = ApiClient.jsonConvertSafe(expanded.isCustom),
                isRequired = ApiClient.jsonConvertSafe(expanded.isRequired),
                fieldType = ApiClient.jsonConvertSafe(expanded.fieldType),
                fieldFormat = ApiClient.jsonConvertSafe(expanded.fieldFormat),
                fieldChoices = ApiClient.jsonConvertSafe(expanded.fieldChoices),
                itemSchema = ApiClient.jsonConvertSafe(expanded.itemSchema)
            )
        }
    }
}

